### ISSUE TITLE
To format the date

### ISSUE THREAD

**Issue by Desgard** [HackSwjtu/weapp-clawjtu#5]
![image](https://cloud.githubusercontent.com/assets/7804535/24580420/8995739c-173a-11e7-951f-ce91af655185.png)

-> `讲座时间：2017-04-04 09:50`

**Comment by WangNianyi2001** [comment]
标题零分！
神tm不定式

**Comment by Desgard** [comment]
@WangNianyi2001 
看得懂就得了。关爱一下六级没过的人。😭😭
